### ISSUE TITLE
递进去的是图像格式

### ISSUE THREAD

**Issue by liuy616161** [broalantaps/RP24-DetectionModel#1]
图像单通道是用的灰度图吗

**Comment by broalantaps** [comment]
> 图像单通道是用的灰度图吗


`input_shape = {1, static_cast<unsigned long>(IMAGE_HEIGHT), static_cast<unsigned long>(IMAGE_WIDTH), 3}; `


---
 
感谢关注，第一个维度是批次大小，最后一个维度才是图像通道数，我们使用的是BGR三通道图，是用opencv BGR2RGB转换成RGB格式后再送入网络。

**Comment by liuy616161** [comment]
感谢！
原以为h文件中的构造函数的modelpath能够使用，才以为是单通道的，谢谢解答！
